config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    scope module: :topics do
      resources :posts, except: [:new, :create]
    end
  end
  get 'posts/new', to: 'topics/posts#new',    as: 'new_post'
  post 'posts',    to: 'topics/posts#create', as: 'create_post'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'static#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_uniqueness_of :slug
  validates_presence_of :title, :slug
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :set_defaults

  validates_presence_of :first_name, :last_name
  validates :username, uniqueness: true, presence: true , format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }

  def full_name
    self.first_name + " " + self.last_name
  end

  private

   def set_defaults
     self.role ||= 'student'
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :username)
    end

    def account_update_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :username)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    @posts = Post.all.limit(25)
    @topics = Topic.all
  end

end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  before_action :set_topic, except: [:new, :create]
  before_action :set_post, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = @topic.posts.page(params[:page]).per(10)
  end

  def show
  end

  def new
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save
      redirect_to topic_post_path(topic_id: post.topic_id, id: post), notice: "Your post was successfully published."
    else
      render :new
    end
  end

  def edit
    if @post.user_id != current_user.id
      redirect_to topic_post_path(topic_id: @post.topic_id, id: @post), notice: "Your are not authorized to edit this post."
    end
  end

  def update

    if @post.update(post_params)
      redirect_to topic_post_path(topic_id: @post.topic_id, id: @post), notice: "Your post was successfully updated."
    else
      render :edit, notice: "There was an error processing your request!"
    end
  end

  private

    def set_topic
      @topic = Topic.friendly.find(params[:topic_id])
    end

    def set_post
      @post = @topic.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :topic_id)
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update]

  def index
    @topics = Topic.page(params[:page]).per(15)
  end

  def show
    redirect_to topic_posts_path(topic_id: @topic)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to topic_posts_path(topic_id: @topic), notice: "Topic was successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topic_posts_path(topic_id: @topic), notice: "Your topic was successfully updated."
    else
      render :edit, notice: "There was an error processing your request!"
    end
  end

  private

    def set_topic
      @topic = Topic.friendly.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def form_route(source)
    return create_post_path if source == 'new'
    return topic_post_path(topic_id: @topic.id, id: @post.id) if source == 'edit'
  end

  def form_action(source)
    return 'post' if source == 'new'
    return 'put' if source == 'edit'
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dailysmarty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_header.html.erb
<div class="grey2"></div>
<div id="header">
  <div class="container">
    <div class="row">
      <div class="grey"></div>
        <a class="col-xs-3 logo pull-left" href="<%= root_url %>"><%= image_tag('common/logo.png') %><%= image_tag('common/logo_small.png', class: 'logo-small') %></a>
        <div class="col-xs-9 pull-left">
          <div class="col-xs-6 pull-left">
            <span class="icon icon-search"></span>
            <input type="text" placeholder="Search.../">
          </div>
          <div class="col-xs-3 avatar pull-right">
            <a href="<%= root_url %>">
              <div class="mask"></div>
              <%= image_tag('common/guest_image.png')%>
            </a>
            <strong>Welcome Guest!</strong>
            <%= link_to "Login", new_user_session_path %> or
            <%= link_to "Register", new_user_registration_path %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<div id="main-menu" class="small">
  <div class="container">
    <div class="row">
    </div>
  </div>
</div>

app/views/shared/_posts.html.erb
<% @posts.each do |post| %>
<li class="clearfix">
  <div class="ratings">
    <a href="#up" class="up"></a>
    <h1>1178</h1>
    <a href="down" class="down"></a>
  </div>

  <div class="article-image">
    <div class="mask"></div>
    <img src="https://s3.amazonaws.com/rails-camp-tutorials/pro-rails/ui/article_image.png"/>
  </div>

  <div class="article-desc">
    <h2><%= link_to post.title, topic_post_path(topic_id: post.topic.slug, id: post) %></h2>
    <p><%= post.content %></p>
    <span>By <strong><%= post.user.username %></strong> <%= post.created_at %></span>
  </div>

  <div class="article-stats">
    <ul class="pull-right">
      <li>
        <span class="icon icon-view"></span>
        <h2>347</h2>
      </li>
      <li>
        <span class="icon icon-comment"></span>
        <h2>347</h2>
      </li>
      <li>
        <span class="icon icon-connection"></span>
        <h2>347</h2>
      </li>
    </ul>
  </div>
</li>
<% end %>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <%= f.text_field :title %>
  <%= f.submit 'Save' %>
<% end %> 

app/views/topics/_topic.html.erb
<div class='col-xs-3 topics text-center'>
  <%= link_to topic.title, topic_posts_path(topic_id: topic) %>
</div>

app/views/topics/edit.html.erb
<%= render partial: 'form', locals: { source: 'edit'} %>

app/views/topics/index.html.erb
<div class="container">
  <div class="row">
    <%= render @topics %>
  </div>
  <%= paginate @topics %>
</div>

app/views/topics/new.html.erb
<%= render partial: 'form', locals: { source: 'new' } %>

app/views/topics/posts/_form.html.erb
<%= form_tag form_route(source), method: form_action(source) do %>
  <%= text_field_tag "post[title]", (@post.title if @post) || "" %>
  <%= text_field_tag "post[content]", (@post.content if @post) || "" %>
  <%= collection_select(:post,
                       :topic_id,
                       Topic.all,
                       :id,
                       :title,
                      { selected: (params[:topic_id] if params[:topic_id])}) %>
  <%= submit_tag 'Save' %>
<% end %>

app/views/topics/posts/edit.html.erb
<%= render partial: 'form', locals: { source: 'edit' } %>

app/views/topics/posts/index.html.erb
<div class="container">

  <h1><%= @topic.title %></h1>
  <div class="row">
    <div class="col-xs-9 pull-left">
      <ul class="articles">
        <%= render 'shared/posts' %>
      </ul>
    </div>
  </div>
  <%= paginate @posts %>
  <%= link_to "New Post", new_post_path(topic_id: @topic.id) %>
</div>

app/views/topics/posts/new.html.erb
<%= render partial: 'form', locals: { source: 'new'} %>

app/views/topics/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9 article-content pull-left">
      <h1 class="col-xs-6 pull-left"><%= @post.title %></h1>
      <span>By <strong><%= @post.user.full_name %></strong> <%= @post.created_at.strftime("Published: on %m/%d/%Y at %l:%M%P") %></span>
      <p><strong>Topic:</strong> <%= @post.topic.title %></p>

      <a href="#show-sidebar" class="btn btn-default btn-green show-sidebar"><span>Show More Details</span></a>

      <div class="clearfix"></div>
      <p class="col-xs-8 first"><%= @post.content %></p>

      <hr />
      <div class="actions">
        <% if current_user && @post.user_id == current_user.id %>
          <%= link_to "Edit Post", edit_topic_post_path(topic_id: @topic.id, id: @post.id), class: 'btn btn-default btn-green' %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-3 article-sidebar pull-right">
      <div class="next-article">
        <div class="btn btn-left"></div>
          <div class="btn btn-right"></div>
            <h1>Scientists find closest thing yet to Earth-sun twin system</h1>
            <span>By <strong>Thomas Gibbons-Neff</strong> and <strong>Carol Morell</strong> June 20 at 4:05 PM</span>
          </div>
      </div>
    </div>
</div>